version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      USERNAME: postgres
      PASSWORD: password
      DATABASE: challenge
      DB_HOST: postgres
      NODE_ENV: production
      JWT_KEY: secretKey
      PORT: 3000
    ports:
      - '3000:3000'
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge
